version: "3.0"

services:
  postgresql:
    image: postgres:10.6
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data